# Generated by Django 2.1 on 2019-01-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
